### ISSUE TITLE
Playlists

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-stream-web#1]
Remove Dropdown on playlist buttons and connect to the right endpoints

**Comment by rassokhin-s** [comment]
Hi Stefan @daebwae !
Dropdown on playlist buttons was meant to open playlists as on screenshot attached. Some of them already have urls, but return 404 error. Topher @topherwhite promised to write some backend stuff for these playlists buttons. Have he already done that?
![screenshot_stanislav 2016-03-14 9 10 11](https://cloud.githubusercontent.com/assets/2122991/13736358/ea638b7c-e9c4-11e5-8218-3b4cfcc37067.png)

**Comment by rassokhin-s** [comment]
Comment from @daebwae: 
"For this we'll only have three playlist streams to start with. For that reason we won't need drop downs yet."
@topherwhite is working on playlists backend.
