### ISSUE TITLE
Play Button in visualization area 

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-stream-web#2]
Add a play button in the visualisation area with an overlay. 

![image](https://cloud.githubusercontent.com/assets/749854/13732245/59676224-e97e-11e5-8ddb-36f5af45c53c.png)

**Comment by rassokhin-s** [comment]
@daebwae If we add this overlay with play button, then at top controls area we will remove play button and stay only pause button. When we pause playback then overlay with play button shows up again... Is it correct?

**Comment by daebwae** [comment]
@rassokhin-s , we think of it more as an additional way to play the stream. You don't need to change the behaviour of the current controls, we just add another way to begin the streaming. If a user has logged in, the first thing they see is a button to start the stream in the center of their screen. Then they can listen to it while exploring the controls on top and below.

**Comment by rassokhin-s** [comment]
@daebwae there is a small logical conflict with #5 issue. Because of autoplay on desktop we will never see this big play button on desktop. So it will be only for tablet/mobile devices, right?

**Comment by rassokhin-s** [comment]
Comment from @daebwae:
"Right! It's only for mobile #5 issue"
