### ISSUE TITLE
Change time display

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-stream-web#3]
In the player controls: use timezone of guardian's location and add label about timezone.

**Comment by rassokhin-s** [comment]
@daebwae as far as I know, I don't have enough information about guardian's timezone. See what data I receive from the server:
<img width="570" alt="screenshot_stanislav 2016-03-14 10 03 11" src="https://cloud.githubusercontent.com/assets/2122991/13737223/a769e872-e9cc-11e5-931c-b75f0e4bbde6.png">
`measured_at` attribute doesn't include timezone data and json doesn't have coordinate attributes.

**Comment by rassokhin-s** [comment]
@daebwae @topherwhite Requires discussion. For current moment I've hardcoded Amazon timezone offset. We need to include additional attributes to json data: timezone offset or coordinates.
